services:
  db:
    image: postgres:15
    container_name: job_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-jobdb}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s

  api:
    build: ./job_aggregator
    container_name: job_api
    restart: unless-stopped
    env_file: 
      - .env.dev
      - .env.hh.dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./job_aggregator/migrations:/app/migrations
      - ./job_aggregator:/app

  bot:
    build: ./job-bot
    container_name: telegram_bot
    restart: unless-stopped
    env_file: .env.dev
    depends_on:
      - api

volumes:
  postgres_data:
